# Use Node base image
FROM node:18

# Install Java (JDK 21)
RUN apt-get update && apt-get install -y openjdk-21-jdk

# Set working directory
WORKDIR /app

# Copy all files into container
COPY . .

# Install dependencies (if any)
RUN npm install

# Expose your port
EXPOSE 5454

# Start your server
CMD ["node", "server.js"]